spring:
  cloud:
    gateway:
      routes: 
        - id: third_party_route
          uri: lb://third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: host_route
          uri: lb://auth-server
          predicates:
            - Host=auth.ml-platform.com

        - id: auth_route
          uri: lb://auth-server
          predicates:
            - Host=auth.ml-platform.com

        - id: member_route_ml
          uri: lb://member
          predicates:
            - Host=member.ml-platform.com

